export const COUNTRIES = {
    GET_PROVINCES_REQUEST: 'GET_PROVINCES_REQUEST',
    GET_PROVINCES_SUCCESS: 'GET_PROVINCES_SUCCESS',
    GET_PROVINCES_FAIL: 'GET_PROVINCES_FAIL',

    GET_DISTRICTS_REQUEST: 'GET_DISTRICTS_REQUEST',
    GET_DISTRICTS_SUCCESS: 'GET_DISTRICTS_SUCCESS',
    GET_DISTRICTS_FAIL: 'GET_DISTRICTS_FAIL',

    GET_WARDS_REQUEST: 'GET_WARDS_REQUEST',
    GET_WARDS_SUCCESS: 'GET_WARDS_SUCCESS',
    GET_WARDS_FAIL: 'GET_WARDS_FAIL',
}