export const POSTS = {
    UPLOAD_POST_IMAGE_REQUEST: 'UPLOAD_POST_IMAGE_REQUEST',

    GET_ALL_POSTS_REQUEST: 'GET_ALL_POSTS_REQUEST',
    GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
    GET_ALL_POSTS_FAIL: 'GET_ALL_POSTS_FAIL',

    CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAIL: 'CREATE_POST_FAIL',
    
    GET_DETAIL_POST_FOR_UPDATE_REQUEST: 'GET_DETAIL_POST_FOR_UPDATE_REQUEST',
    GET_DETAIL_POST_FOR_UPDATE_SUCCESS: 'GET_DETAIL_POST_FOR_UPDATE_SUCCESS',
    GET_DETAIL_POST_FOR_UPDATE_FAIL: 'GET_DETAIL_POST_FOR_UPDATE_FAIL',

    UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAIL: 'UPDATE_POST_FAIL',

    GET_DETAIL_POST_REQUEST: 'GET_DETAIL_POST_REQUEST',
    GET_DETAIL_POST_SUCCESS: 'GET_DETAIL_POST_SUCCESS',
    GET_DETAIL_POST_FAIL: 'GET_DETAIL_POST_FAIL',

    DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAIL: 'DELETE_POST_FAIL',

    COMMENT_REQUEST: 'COMMENT_REQUEST',
    COMMENT_SUCCESS: 'COMMENT_SUCCESS',
    COMMENT_FAIL: 'COMMENT_FAIL',

    RATE_REQUEST: 'RATE_REQUEST',
    RATE_SUCCESS: 'RATE_SUCCESS',
    RATE_FAIL: 'RATE_FAIL',

    FOLLOW_REQUEST: 'FOLLOW_REQUEST',
    FOLLOW_SUCCESS: 'FOLLOW_SUCCESS',
    FOLLOW_FAIL: 'FOLLOW_FAIL',
}