export const PAYMENTS = {
    GET_ALL_PAYMENTS_REQUEST: 'GET_ALL_PAYMENTS_REQUEST',
    GET_ALL_PAYMENTS_SUCCESS: 'GET_ALL_PAYMENTS_SUCCESS',
    GET_ALL_PAYMENTS_FAIL: 'GET_ALL_PAYMENTS_FAIL',

    CREATE_PAYMENT_REQUEST: 'CREATE_PAYMENT_REQUEST',
    CREATE_PAYMENT_SUCCESS: 'CREATE_PAYMENT_SUCCESS',
    CREATE_PAYMENT_FAIL: 'CREATE_PAYMENT_FAIL',
}