export const POSTAGE = {
    CREATE_POSTAGE_REQUEST: 'CREATE_POSTAGE_REQUEST',
    CREATE_POSTAGE_SUCCESS: 'CREATE_POSTAGE_SUCCESS',
    CREATE_POSTAGE_FAIL: 'CREATE_POSTAGE_FAIL',

    GET_ALL_POSTAGES_REQUEST: 'GET_ALL_POSTAGES_REQUEST',
    GET_ALL_POSTAGES_SUCCESS: 'GET_ALL_POSTAGES_SUCCESS',
    GET_ALL_POSTAGES_FAIL: 'GET_ALL_POSTAGES_FAIL',

    DELETE_POSTAGE_REQUEST: 'DELETE_POSTAGE_REQUEST',
    DELETE_POSTAGE_SUCCESS: 'DELETE_POSTAGE_SUCCESS',
    DELETE_POSTAGE_FAIL: 'DELETE_POSTAGE_FAIL',
}

export const postageTypes = [ "", "Gói 01 ngày", "Gói 30 ngày" ];