export const CATEGORIES = {
    CATEGORY_ADD_REQUEST: 'CATEGORY_ADD_REQUEST',
    CATEGORY_ADD_SUCCESS: 'CATEGORY_ADD_SUCCESS',
    CATEGORY_ADD_FAIL: 'CATEGORY_ADD_FAIL',

    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAIL: 'GET_ALL_CATEGORIES_FAIL',

    GET_DETAIL_CATEGORY_REQUEST: 'GET_DETAIL_CATEGORY_REQUEST',
    GET_DETAIL_CATEGORY_SUCCESS: 'GET_DETAIL_CATEGORY_SUCCESS',
    GET_DETAIL_CATEGORY_FAIL: 'GET_DETAIL_CATEGORY_FAIL',

    UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAIL: 'UPDATE_CATEGORY_FAIL',

    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAIL: 'DELETE_CATEGORY_FAIL',

    GET_ALL_CATEGORIES_NO_PAGINATION_REQUEST: 'GET_ALL_CATEGORIES_NO_PAGINATION_REQUEST',
    GET_ALL_CATEGORIES_NO_PAGINATION_SUCCESS: 'GET_ALL_CATEGORIES_NO_PAGINATION_SUCCESS',
    GET_ALL_CATEGORIES_NO_PAGINATION_FAIL: 'GET_ALL_CATEGORIES_NO_PAGINATION_FAIL',
}